//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_ITSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_siskom_smeasEntities : DbContext
    {
        public db_siskom_smeasEntities()
            : base("name=db_siskom_smeasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<@class> classes { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<violation_categories> violation_categories { get; set; }
        public DbSet<violation_records> violation_records { get; set; }
    }
}
