//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_ITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.violation_records = new HashSet<violation_records>();
        }
    
        public int id_student { get; set; }
        public string nisn { get; set; }
        public string full_name { get; set; }
        public int id_class { get; set; }
        public string gender { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual ICollection<violation_records> violation_records { get; set; }
    }
}
