//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_ITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class violation_records
    {
        public int id_record { get; set; }
        public int id_student { get; set; }
        public int id_category { get; set; }
        public int id_reporter_user { get; set; }
        public System.DateTime violation_date { get; set; }
        public string description { get; set; }
        public string counseling_status { get; set; }
    
        public virtual student student { get; set; }
        public virtual user user { get; set; }
        public virtual violation_categories violation_categories { get; set; }
    }
}
