//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_ITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class violation_categories
    {
        public violation_categories()
        {
            this.violation_records = new HashSet<violation_records>();
        }
    
        public int id_category { get; set; }
        public string category_name { get; set; }
        public string severity_level { get; set; }
        public int default_point { get; set; }
    
        public virtual ICollection<violation_records> violation_records { get; set; }
    }
}
